// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: array_cursor_iterator.gen.go.tmpl

package tsm1

import (
	"context"

	"github.com/influxdata/influxdb/v2/influxql/query"
	"github.com/influxdata/influxdb/v2/models"
	"github.com/influxdata/influxdb/v2/tsdb"
)

// buildFloatArrayCursor creates an array cursor for a float field.
func (arrayCursorIterator *arrayCursorIterator) buildFloatArrayCursor(ctx context.Context, name []byte, tags models.Tags, field string, opt query.IteratorOptions) tsdb.FloatArrayCursor {
	key := arrayCursorIterator.seriesFieldKeyBytes(name, tags, field)
	cacheValues := arrayCursorIterator.engine.Cache.Values(key)
	keyCursor := arrayCursorIterator.engine.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	if opt.Ascending {
		if arrayCursorIterator.asc.Float == nil {
			arrayCursorIterator.asc.Float = newFloatArrayAscendingCursor()
		}
		arrayCursorIterator.asc.Float.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.asc.Float
	} else {
		if arrayCursorIterator.desc.Float == nil {
			arrayCursorIterator.desc.Float = newFloatArrayDescendingCursor()
		}
		arrayCursorIterator.desc.Float.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.desc.Float
	}
}

// buildIntegerArrayCursor creates an array cursor for a integer field.
func (arrayCursorIterator *arrayCursorIterator) buildIntegerArrayCursor(ctx context.Context, name []byte, tags models.Tags, field string, opt query.IteratorOptions) tsdb.IntegerArrayCursor {
	key := arrayCursorIterator.seriesFieldKeyBytes(name, tags, field)
	cacheValues := arrayCursorIterator.engine.Cache.Values(key)
	keyCursor := arrayCursorIterator.engine.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	if opt.Ascending {
		if arrayCursorIterator.asc.Integer == nil {
			arrayCursorIterator.asc.Integer = newIntegerArrayAscendingCursor()
		}
		arrayCursorIterator.asc.Integer.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.asc.Integer
	} else {
		if arrayCursorIterator.desc.Integer == nil {
			arrayCursorIterator.desc.Integer = newIntegerArrayDescendingCursor()
		}
		arrayCursorIterator.desc.Integer.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.desc.Integer
	}
}

// buildUnsignedArrayCursor creates an array cursor for a unsigned field.
func (arrayCursorIterator *arrayCursorIterator) buildUnsignedArrayCursor(ctx context.Context, name []byte, tags models.Tags, field string, opt query.IteratorOptions) tsdb.UnsignedArrayCursor {
	key := arrayCursorIterator.seriesFieldKeyBytes(name, tags, field)
	cacheValues := arrayCursorIterator.engine.Cache.Values(key)
	keyCursor := arrayCursorIterator.engine.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	if opt.Ascending {
		if arrayCursorIterator.asc.Unsigned == nil {
			arrayCursorIterator.asc.Unsigned = newUnsignedArrayAscendingCursor()
		}
		arrayCursorIterator.asc.Unsigned.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.asc.Unsigned
	} else {
		if arrayCursorIterator.desc.Unsigned == nil {
			arrayCursorIterator.desc.Unsigned = newUnsignedArrayDescendingCursor()
		}
		arrayCursorIterator.desc.Unsigned.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.desc.Unsigned
	}
}

// buildStringArrayCursor creates an array cursor for a string field.
func (arrayCursorIterator *arrayCursorIterator) buildStringArrayCursor(ctx context.Context, name []byte, tags models.Tags, field string, opt query.IteratorOptions) tsdb.StringArrayCursor {
	key := arrayCursorIterator.seriesFieldKeyBytes(name, tags, field)
	cacheValues := arrayCursorIterator.engine.Cache.Values(key)
	keyCursor := arrayCursorIterator.engine.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	if opt.Ascending {
		if arrayCursorIterator.asc.String == nil {
			arrayCursorIterator.asc.String = newStringArrayAscendingCursor()
		}
		arrayCursorIterator.asc.String.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.asc.String
	} else {
		if arrayCursorIterator.desc.String == nil {
			arrayCursorIterator.desc.String = newStringArrayDescendingCursor()
		}
		arrayCursorIterator.desc.String.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.desc.String
	}
}

// buildBooleanArrayCursor creates an array cursor for a boolean field.
func (arrayCursorIterator *arrayCursorIterator) buildBooleanArrayCursor(ctx context.Context, name []byte, tags models.Tags, field string, opt query.IteratorOptions) tsdb.BooleanArrayCursor {
	key := arrayCursorIterator.seriesFieldKeyBytes(name, tags, field)
	cacheValues := arrayCursorIterator.engine.Cache.Values(key)
	keyCursor := arrayCursorIterator.engine.KeyCursor(ctx, key, opt.SeekTime(), opt.Ascending)
	if opt.Ascending {
		if arrayCursorIterator.asc.Boolean == nil {
			arrayCursorIterator.asc.Boolean = newBooleanArrayAscendingCursor()
		}
		arrayCursorIterator.asc.Boolean.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.asc.Boolean
	} else {
		if arrayCursorIterator.desc.Boolean == nil {
			arrayCursorIterator.desc.Boolean = newBooleanArrayDescendingCursor()
		}
		arrayCursorIterator.desc.Boolean.reset(opt.SeekTime(), opt.StopTime(), cacheValues, keyCursor)
		return arrayCursorIterator.desc.Boolean
	}
}
